REPO BUG
Try to build SmsTicket.Mobile - Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(27360,96,27360,114): error CS0234: The type or namespace name 'SwipeRefreshLayout' does not exist in the namespace 'AndroidX' (are you missing an assembly reference?)
5>